---
- name: Set console timeout
  bigip_sys_global:
   console_timeout: "{{ f5_console_timeout }}"
   password: "{{ f5_passwd }}"
   server: "{{ f5_host }}"
   user: "{{ f5_user }}"
   state: present
   validate_certs: "{{ f5_validate_certs }}" 
  delegate_to: "{{ f5_delegate_to }}"
  when: (f5_console_timeout is defined) and
        (f5_console_timeout | length) > 0
  tags: set_gui
  notify: config sync

- name: Set gui banner
  bigip_sys_global:
   banner_text: "{{ f5_gui_banner }}"
   password: "{{ f5_passwd }}"
   server: "{{ f5_host }}"
   user: "{{ f5_user }}"
   state: present
   validate_certs: "{{ f5_validate_certs }}" 
  delegate_to: "{{ f5_delegate_to }}"
  when: (f5_gui_banner is defined) and
        (f5_gui_banner | length) > 0
  tags: set_gui
  notify: config sync

- name: Set httpd idle timeout
  bigip_device_httpd:
   auth_pam_idle_timeout: "{{ f5_gui_idle_timeout }}"
   password: "{{ f5_passwd }}"
   server: "{{ f5_host }}"
   user: "{{ f5_user }}"
   validate_certs: "{{ f5_validate_certs }}"
  delegate_to: "{{ f5_delegate_to }}"
  when: (f5_gui_idle_timeout is defined) and
        (f5_gui_idle_timeout | length) > 0
  tags: set_gui
  notify: config sync
 
- name: Set httpd authentication realm
  bigip_device_httpd:
   auth_name: "{{ f5_gui_auth_realm }}"
   password: "{{ f5_passwd }}"
   server: "{{ f5_host }}"
   user: "{{ f5_user }}"
   validate_certs: "{{ f5_validate_certs }}"
  delegate_to: "{{ f5_delegate_to }}"
  when: (f5_gui_auth_realm is defined) and
        (f5_gui_auth_realm | length) > 0
  tags: set_gui
  notify: config sync

- name: Set httpd ssl protocols
  bigip_device_httpd:
   ssl_protocols: "{{ f5_gui_ssl_protocols }}"
   password: "{{ f5_passwd }}"
   server: "{{ f5_host }}"
   user: "{{ f5_user }}"
   validate_certs: "{{ f5_validate_certs }}"
  delegate_to: "{{ f5_delegate_to }}"
  when: (f5_gui_ssl_protocols is defined) and
        (f5_gui_ssl_protocols | length) > 0
  tags: set_gui
  notify: config sync

- name: Set httpd ssl ciphers suite
  bigip_device_httpd:
   ssl_cipher_suite: "{{ f5_gui_ssl_ciphers_suite }}"
   password: "{{ f5_passwd }}"
   server: "{{ f5_host }}"
   user: "{{ f5_user }}"
   validate_certs: "{{ f5_validate_certs }}"
  delegate_to: "{{ f5_delegate_to }}"
  when: (f5_gui_ssl_ciphers_suite is defined) and
        (f5_gui_ssl_ciphers_suite | length) > 0
  tags: set_gui
  notify: config sync

- name: Set httpd allowed clients networks
  bigip_device_httpd:
   allow: "{{ f5_gui_authorized_subnets }}"
   password: "{{ f5_passwd }}"
   server: "{{ f5_host }}"
   user: "{{ f5_user }}"
   validate_certs: "{{ f5_validate_certs }}"
  delegate_to: "{{ f5_delegate_to }}"
  when: (f5_gui_authorized_subnets is defined) and
        (f5_gui_authorized_subnets | length) > 0
  tags: set_gui
  notify: config sync
