---
# handlers file for f5.hardening
- name: save config
  bigip_config: 
   save: yes
   password: "{{ f5_passwd }}"
   server: "{{ f5_host }}"
   user: "{{ f5_user }}"
   validate_certs: "{{ f5_validate_certs }}"
  delegate_to: "{{ f5_delegate_to }}"

- name: config sync
  bigip_configsync_action:
   device_group: "{{ item.name }}"
   sync_device_to_group: yes
   password: "{{ f5_passwd }}"
   server: "{{ f5_host }}"
   user: "{{ f5_user }}"
   validate_certs: "{{ f5_validate_certs }}"
  delegate_to: "{{ f5_delegate_to }}"
  when: f5_ha_status == 'cluster'
  loop: "{{ f5_device_groups }}"
  
